### ISSUE TITLE
UI monorepo

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next#117] opened 2016-04-03 10:46 UTC
We use around 20-25 Next (n- and next-) front end packages per app and around the same again for Origami o- components. I've been thinking a lot recently about how I would personally like to develop our front end code.

I think a monorepo approach for the Next UI could improve our development efficiency, consistency and reliability and maybe more. The [Babel project](https://github.com/babel/babel/blob/master/doc/design/monorepo.md) lists the following benefits:

- Single lint, build, test and release process.
- Easy to coordinate changes across modules.
- Single place to report issues.
- Easier to setup a development environment.
- Tests across modules are ran together which finds bugs that touch multiple modules easier.

Obviously that's a JavaScript project and doesn't have the concerns of resolving template partials and maintaining clean CSS. However, I think they still broadly apply and I can think of/cherry pick a few more possible positives:

## Better maintainability?

o-ft-icons is [liberally used around our projects](https://github.com/search?l=json&q=org%3AFinancial-Times+o-ft-icons&ref=searchresults&type=Code) as a dependency of apps, of components and dependencies of dependencies. The same is true for a few other fundamental components.

When a major version of these Origami components is released rolling it out is very difficult. Synchronising changes across multiple component and app repos is nightmarish. Imagine finding an issue with your changes when you thought you were nearly done! With a monorepo the necessary changes could be made with a single pull request and new versions of components affected [released simultaneously](https://github.com/kittens/lerna). Downstream dependents may then bump their packages and make necessary changes in a single pull request also.

## Better oversight and visibility?

We currently duplicate CSS code _a lot_. Sometimes this is via mixins and sometimes this may be because we don't realise the solution already exists in another component. Nobody has visibility over every component repo.

In the case of mixins this can be cleaned up (sort of) with tooling, with the knowledge that this may create side effects as it must break the cascade as authored. However, with a monorepo we could encourage the use of shared class names because there is better oversight over their usage. We can more confidently use class names from Origami components too (IE. using `class="o-button"` in the markup rather than including the Origami component in silent mode and applying the mixin to a custom class name) creating less duplication.

With more people working in a shared space there is also an improved chance of catching repetition at the pull review stage and more likely to point out changes that may break an integration elsewhere.

## Easier development?

From past experience I am of the opinion that working on UI components in the isolation of a styleguide was quite productive, aided documentation and encouraged collaboration from designers... I guess this stuff has been written again and again by anybody who has had a decent styleguide/component library so it doesn't need repeating here.

My favourite feature _by far_ is the ability to display every conceivable variation in one place so the effects of changes can be seen quickly.

An important point is that the styleguide implementation itself becomes a minor detail. With all components in a single place it's straightforward to generate and always up-to-date.

**Comment by matthew-andrews** [comment] 2016-04-04 07:53
I'd support any effort to experiment to find a better way to achieve the above aims.

I think there have been some costs of this approach have been overlooked here.  Babel does has the advantage of a standards process that discusses+polices the potential features of JavaScript at great length.  Internal mono-repos that I have worked with before have always (and very quickly) become a dumping ground of all sorts of things, different bits of code get very tightly coupled with each other, also they are very difficult to share across different teams, because they are simply too big and complex to justify bringing into a small project.  I also think _some_ of the advantage you list could also be achieved in a repo-per-component world just with different approach to and more investment in the tooling (e.g. generation of style guide, acid test pages)

Also we **cannot** ignore Origami.  FT readers don't distinguish stuff on `www.`/`next.` from different FT.com subdomains or distinguish between what we internally refer to as different products.  They see one FT.  It is a **critical** part of our responsibilities in Next to support the Origami team to take our UI elements and make them reusable (this doesn't rule out a mono-repo approach, the benefits you cite there could be as much as benefit to them as it could be to us) but we must work increasingly with Origami and not against them.

I cannot emphasise this point enough.  If we beautiful a beautiful Next that our customers love but moving between that and the rest of the FT's online properties is a clunky, disjointed and confusing experience **we will have failed**.

Is there a small way we can experiment with the approach you describe?  (Perhaps building on / merging `next-sass/js-setup`?)

**Comment by i-like-robots** [comment] 2016-04-04 10:07
> dumping ground of all sorts of things 

This is certainly true but solvable with discipline and proper oversight. A counter may be we currently lack a dumping ground which encourages repetition.

> Also we cannot ignore Origami

My secondary motivation for raising this is about Origami. I think it makes the integration of Origami components much easier and should bring some of our components closer to theirs.

> Is there a small way we can experiment with the approach you describe?

It may be possible to cobble it together using submodules... if there's buy in from any others I'm sure we could copy and paste things around and see how it goes.

**Comment by wheresrhys** [comment] 2016-04-07 14:41
can the monorepo approach work with bower, which is repo and tag based?

**Comment by wheresrhys** [comment] 2016-04-07 14:59
sass-setup was intended as a solution for the o-ft-icons sort of thing. Sass-setup includes all the origami and next 'atoms', manages their versions. There are limitations to this, but it's made less effective because components and apps are also requiring & resolving these atoms themselves. If we crack down on that the problem reduces. I also feel we should both listen and influence more regarding the origami versioning process e.g. decision made lately to major version whenever a component declares a new dependency (good reasons for it, but it's a decision made to benefit buildservice users, and makes things harder for us and other origami self-builders); recent major release of o-ft-icons, problems could perhaps have been mitigated by releasing o-icons with the new api (which is gonna happen anyway)

Are you saying all UI for all our front-end apps should live in one repo, or just the stuff which is already shared (via components) between many apps? The latter is probably workable, but is not very different from what we have already. The former I think will bring as much if not more pain to the development worflow, e.g. will mean bower linking to the next-ui component even if you're working on ui code specific to just that app, resolving nasty merge commits with the whole next team.

By monorepo do you mean a single repo that holds the source for numerous components, each of which are published separately? If so, can this work with bower, which is repo and git tag based

**Comment by i-like-robots** [comment] 2016-04-07 15:17
> it's made less effective because components and apps are also requiring & resolving these atoms themselves

Yes, definitely... maybe we could make an effort to tackle this first and see if that helps? I find it interesting too that we tend to use mixins rather than the available class names (when silent mode is off)

> Are you saying all UI for all our front-end apps should live in one repo, or just the stuff which is already shared

_Definitely_ just shared stuff! The usual abstraction test will do: "do _really_ you need it more than twice?"

> By monorepo do you mean a single repo that holds the source for numerous components, each of which are published separately?

Yes. I like the idea of offering 'presets' as well.

> can this work with bower

I don't know... maybe not =S I'm not aware that anybody is particularly wedded to Bower so if there turns out to be support for the idea of a monorepo maybe the issue can be sidestepped. This is a shockingly poor answer akin to [this](https://adactio.com/journal/10467).

**Comment by wheresrhys** [comment] 2016-04-07 15:25
bower is needed because
a) guarantees flat file structure (for templating)
b) compatible with origami

**Comment by i-like-robots** [comment] 2016-04-07 15:40
a) Yes... I suppose NPM 3 also guarantees it because all packages will be installed at the top level except duplicates for packages pinned to different versions. There's no way we could rely on this to always do what we want though =(

b) True. Nothing stopping the packages being published on X/Y/Z but they busy enough as is!

I will look into it and how bad any workarounds may be. Whilst I'm not fond of Bower I appreciate the separation of client and server.

**Comment by i-like-robots** [comment] 2016-04-07 15:43
Interesting discussion here of suitcss reorganisation https://github.com/suitcss/suit/issues/109

**Closed** 2016-08-19 09:18 UTC
